services:
    mariadb:
            container_name: mariadb
            networks:
                - mynetwork
            expose:
                - "3306"
            env_file:
                - .env
            build:
                context: requirements/mariadb
                dockerfile: Dockerfile
            restart: unless-stopped
            volumes:
                - mariadb:/var/lib/mysql

    nginx:
        container_name: nginx
        networks:
            - mynetwork
        ports:
            - "443:443"
        env_file:
            - .env
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/wordpress

    wordpress:
        container_name: wordpress
        networks:
            - mynetwork
        env_file:
            - .env
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress
        expose:
            - "9000"

networks:
    mynetwork:
        driver: bridge

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '/home/npatron/data/mariadb/'
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/npatron/data/wordpress/'